Solve:

\begin{align*}
  x + 2y + z &= 8 \\
  2x -1y + 3z &= 9 \\
  3x - y +2z &= 11 \\
\end{align*}

or

$$
\underline{\bf A}
\begin{pmatrix} x\\ y \\ z \end{pmatrix}= 
\underline{\bf b}
\text{ where }
\underline{\bf A} =
\begin{pmatrix}
1 & 2 & 1 \\ 2 & -1 & 3 \\ 3 & 1 & 2
\end{pmatrix}
\text{ and }
\underline{\bf b} = 
\begin{pmatrix} 8 \\ 9 \\ 11 \end{pmatrix}
$$

through Gaussian Elimination

In [1]:
import numpy as np

In [9]:
Ab = np.array([[1., 2., 1., 8.], [2,-1,3,9], [3,1,2,11]])
Ab

array([[ 1.,  2.,  1.,  8.],
       [ 2., -1.,  3.,  9.],
       [ 3.,  1.,  2., 11.]])

In [10]:
Ab[1] = Ab[1] - 2*Ab[0]
Ab

array([[ 1.,  2.,  1.,  8.],
       [ 0., -5.,  1., -7.],
       [ 3.,  1.,  2., 11.]])

In [11]:
Ab[2] = Ab[2] - 3*Ab[0]
Ab

array([[  1.,   2.,   1.,   8.],
       [  0.,  -5.,   1.,  -7.],
       [  0.,  -5.,  -1., -13.]])

In [12]:
Ab[2] = Ab[2] - Ab[1]
Ab

array([[ 1.,  2.,  1.,  8.],
       [ 0., -5.,  1., -7.],
       [ 0.,  0., -2., -6.]])

Last row:

$$-2 z= -6 \to z=3$$

Next row above:

$$
  -5y + z=-7 \to -5y+3=-7 \to -5y=-10 \to y=2
$$

First row:
$$
x+2y+z=8 \to x + 4+ 3 =8 \to x=1
$$

In [13]:
Ab = np.array([[1., 2., 1., 8.], [2,-1,3,9], [3,1,2,11]])
A = Ab[:,:3]
b = Ab[:,3]
xyz = [1, 2, 3]
print("A x = ", A@xyz)
print("b = ", b)

A x =  [ 8.  9. 11.]
b =  [ 8.  9. 11.]
